version: '3.0'
networks:
  app:
    driver: bridge


volumes:
  db-data:
    driver: local
  redis-data:
    driver: local
  kafka-data:
    driver: local
  zookeeper-data:
    driver: local
  debezium-data:
    driver: local


services:
  generator:
    image: 'extoozy/data-generator-service:latest'
    networks:
      - app
    depends_on:
      - kafka
    env_file:
      - .env
    ports:
      - '8081:8081'

  analyzer:
    image: 'extoozy/data-analyzer-service:latest'
    networks:
      - app
    depends_on:
      - postgres
      - kafka
    env_file:
      - .env
    ports:
      - '8082:8082'

  store:
    image: 'extoozy/data-store-service:latest'
    networks:
      - app
    depends_on:
      - redis
      - kafka
      - debezium
    env_file:
      - .env
    ports:
      - '8083:8083'

  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    networks:
      - app
    env_file:
      - .env
    ports:
      - '2181:2181'
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data

  kafka:
    image: 'confluentinc/cp-kafka:latest'
    networks:
      - app
    env_file:
      - .env
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    volumes:
      - kafka-data:/var/lib/kafka/data

  postgres:
    image: 'postgres:latest'
    networks:
      - app
    env_file:
      - .env
    ports:
      - '5437:5432'
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: "redis:7.2-rc-alpine"
    networks:
      - app
    env_file:
      - .env
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-data:/data

  debezium:
    image: "debezium/connect:2.4.0.Final"
    networks:
      - app
    depends_on:
      - kafka
    environment:
      - BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - GROUP_ID=${DEBEZIUM_KAFKA_BROKER_ID}
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
    user: root
    volumes:
      - debezium-data:/debezium/data
      - ./conf/:/on-startup/